
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'F022C46B52FF7682A7356E1B8938B8ED'
    
_lr_action_items = {'TRANS':([9,10,],[13,-7,]),'FARM':([9,10,],[11,-7,]),'INTEGER':([0,5,],[5,10,]),'SEQ':([0,],[2,]),'WHOLE':([9,10,],[12,-7,]),'$end':([0,1,2,3,4,6,7,8,11,12,13,14,],[-12,-3,-1,0,-4,-5,-6,-2,-8,-10,-11,-9,]),'MANU':([9,10,],[14,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'whole':([0,],[4,]),'trans':([0,],[6,]),'manu':([0,],[1,]),'empty':([0,],[7,]),'farm':([0,],[8,]),'data':([0,],[9,]),'start':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> SEQ','start',1,'p_start','PLYproj.py',53),
  ('start -> farm','start',1,'p_start','PLYproj.py',54),
  ('start -> manu','start',1,'p_start','PLYproj.py',55),
  ('start -> whole','start',1,'p_start','PLYproj.py',56),
  ('start -> trans','start',1,'p_start','PLYproj.py',57),
  ('start -> empty','start',1,'p_start','PLYproj.py',58),
  ('data -> INTEGER INTEGER','data',2,'p_data','PLYproj.py',66),
  ('farm -> data FARM','farm',2,'p_farm','PLYproj.py',70),
  ('manu -> data MANU','manu',2,'p_manu','PLYproj.py',74),
  ('whole -> data WHOLE','whole',2,'p_whole','PLYproj.py',78),
  ('trans -> data TRANS','trans',2,'p_trans','PLYproj.py',82),
  ('empty -> <empty>','empty',0,'p_empty','PLYproj.py',86),
]
